=== samschaust/ISyE-Courses/Details.dtd
<!ELEMENT inventory (ISyE-courses)>
<!ELEMENT course (title, id, description, prerequisites, semester, units, format, instructor, start, end)>
<!ATTLIST course subject (math, physics, writing, chemistry, industrial engineering, computer sciences, economics) #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT prerequisites (#PCDATA)>
<!ELEMENT semester (#PCDATA)>
<!ELEMENT units (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT instructor (#PCDATA)>
<!ATTLIST instructor name (class 1, class 2, class 3) #REQUIRED>
<!ELEMENT location (#PCDATA)>
<!ATTLIST location room (class 1, class 2, class 3) #REQUIRED>
<!ELEMENT time (#PCDATA)>
<!ATTLIST time class (class 1, class 2, class 3) #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>

=== samschaust/ISyE-Courses/Undergraduate.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="styles.css" ?>
<!DOCTYPE catalogue SYSTEM "Details.dtd">

<inventory>
    <course subject="math">
      <title>CSE Calculus I</title>
      <id>MATH 1371</id>
      <description>Differentiation of single-variable functions, basics of integration of single-variable functions. Applications: max-min, related rates, area, curve-sketching. Use of calculator, cooperative learning.</description>
      <prerequisites>CSE or pre-bioprod concurrent registration is required (or allowed) in biosys engn (PRE), background in [precalculus, geometry, visualization of functions/graphs], instr consent; familiarity with graphing calculators recommende</prerequisites>
      <semester>Fall</semester>
      <units>4 units</units>
      <format>In person</format>
      <instructor name="class 1">Prof. Zhilin Luo</instructor>
      <instructor name="class 2">Prof. Jie Min</instructor>
      <instructor name="class 3">Prof. Wuzhe Xu</instructor>
      <location room="class 1">Tate Hall 120</location>
      <location room="class 2">Appleby Hall 302</location>
      <location room="class 3">Vincent Hall 2</location>
      <time class="class 1">Tuesday, 9:05AM to 9:55AM and Thursday, 9:05AM to 11AM</time>
      <time class="class 2">Tuesday, 11:15AM to 12:05PM and Thursday, 11:15AM to 1:10PM</time>
      <start>9/3/2019</start>
      <end>12/11/2019</end>
    </course>

    <course subject="physics">
      <title>Introductory Physics for Science and Engineering I</title>
      <id>PHYS 1301W</id>
      <description>Use of fundamental principles to solve quantitative problems. Motion, forces, conservation principles, structure of matter. Applications to mechanical systems.</description>
      <prerequisites>concurrent registration is required (or allowed) in Math 1271 or concurrent registration is required (or allowed) in Math 1371 or concurrent registration is required (or allowed) in Math 1571</prerequisites>
      <semester>Fall</semester>
      <units>4 units</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Lis Stolik Valor</instructor>
      <instructor name="class 2">Prof. Elliot Bell</instructor>
      <instructor name="class 3">Prof. Yu Xu</instructor>
      <location room="class 1">Tate Hall B63</location>
      <location room="class 2">Tate Hall B26</location>
      <location room="class 3">Tate Hall B26</location>
      <time class="class 1">Tuesday, 9:05AM to 11:00AM and Thursday, 8:00AM to 8:50AM</time>
      <time class="class 2">Tuesday, 11:15AM to 1:10PM and Thursday, 8:00AM to 8:50AM</time>
      <time class="class 3">Tuesday, 1:25PM to 3:20PM and Thursday, 8:00AM to 8:50AM</time>
      <start>9/3/2019</start>
      <end>12/11/2019</end>
    </course>

    <course subject="writing">
      <title>University Writing</title>
      <id>WRIT 1301</id>
      <description>Drafting, revising, editing. Academic genres. Critical reading, rhetorical analysis for principles of audience, purpose, and argumentative strategies. Emphasizes electronic/print library. Critical analysis, annotated bibliography, research paper.</description>
      <prerequisites>Placement in Writ 1301</prerequisites>
      <semester>Fall</semester>
      <units>4 units</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Sarah Selz</instructor>
      <instructor name="class 2">Prof. Sarah Selz</instructor>
      <instructor name="class 3">Prof. Nicole Montanta</instructor>
      <location room="class 1">Vincent Hall 301</location>
      <location room="class 2">Vincent Hall 364</location>
      <location room="class 3">Vruininks Hall 119</location>
      <time class="class 1">Monday, Tuesday, Thursday, Friday, 9:05AM to 9:55AM</time>
      <time class="class 2">Monday, Tuesday, Thursday, Friday, 10:10AM to 11:AM</time>
      <time class="class 3">Monday, Tuesday, Thursday, Friday, 1:25PM to 3:20PM</time>
      <start>9/3/2019</start>
      <end>12/11/2019</end>
    </course>

    <course subject="math">
      <title>Calculus II</title>
      <id>MATH 1372</id>
      <description>Techniques of integration. Calculus involving transcendental functions, polar coordinates, Taylor polynomials, vectors/curves in space, cylindrical/spherical coordinates. Use of calculators, cooperative learning.</description>
      <prerequisites>Grade of at least C- in [1371 or equiv], CSE or pre-Bioprod/Biosys Engr</prerequisites>
      <semester>Spring</semester>
      <units>4 units</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Olivia Cannon</instructor>
      <instructor name="class 2">Prof. Wei Wang</instructor>
      <instructor name="class 3">Prof. Olivia Cannon</instructor>
      <location room="class 1">Tate Hall 120</location>
      <location room="class 2">Lind Hall 229</location>
      <location room="class 3">Vincent Hall 20</location>
      <time class="class 1">Tuesday, 8:00AM to 8:50AM and Thursday, 8:00AM to 9:55AM</time>
      <time class="class 2">Tuesday, 9:05AM to 9:55AM and Thursday, 8:00AM to 9:55AM</time>
      <time class="class 3">Tuesday, 10:10AM to 11:00AM and Thursday, 11:15AM to 1:10PM</time>
      <start>1/21/2020</start>
      <end>5/4/2020</end>
    </course>

    <course subject="physics">
      <title>Introductory Physics for Science and Engineering II</title>
      <id>PHYS 1302W</id>
      <description>Use of fundamental principles to solve quantitative problems. Motion, forces, conservation principles, fields, structure of matter. Applications to electromagnetic phenomena.</description>
      <prerequisites>1301W, concurrent registration is required (or allowed) in Math 1272 or Math 1372 or Math 1572</prerequisites>
      <semester>Spring</semester>
      <units>4 units</units>
      <format>in Person</format>
      <instructor name="class 1">Prof. Paul Haines</instructor>
      <instructor name="class 2">Prof. Marvin Marshak</instructor>
      <instructor name="class 3">Prof. Clement Pryke</instructor>
      <location room="class 1">Tate Hall B50</location>
      <location room="class 2">Tate Hall B50</location>
      <location room="class 3">Tate Hall B50</location>
      <time class="class 1">Monday, Tuesday, Wednesday, Friday, 8:00AM to 8:50AM</time>
      <time class="class 2">Monday, Tuesday, Wednesday, Friday, 10:10AM to 11:00AM</time>
      <time class="class 3">Monday, Tuesday, Wednesday, Friday, 11:15AM to 12:05AM</time>
      <start>1/21/2020</start>
      <end>5/4/2020</end>
    </course>

    <course subject="chemistry">
      <title>Chemical Principles I</title>
      <id>CHEM 1061</id>
      <description>Atomic theory, periodic properties of elements. Thermochemistry, reaction stoichiometry. Behavior of gases, liquids, and solids. Molecular/ionic structure/bonding. Organic chemistry and polymers. energy sources, environmental issues related to energy use.</description>
      <prerequisites>Grade of at least C- in [1011 or 1015] or [passing placement exam, concurrent registration is required (or allowed) in 1065]; intended for science or engineering majors; concurrent registration is required (or allowed) in 1065; registration for 1065 must precede registration for 1061</prerequisites>
      <semester>Spring</semester>
      <units>3 units</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Debra Salmon</instructor>
      <instructor name="class 2">Prof. Doreen Leopold</instructor>
      <instructor name="class 3">Prof. Doreen Leopold</instructor>
      <location room="class 1">Smith Hall 100</location>
      <location room="class 2">Smith Hall 100</location>
      <location room="class 3">Smith Hall 100</location>
      <time class="class 1">Monday, Wednesday, Friday, 8:00AM to 8:50AM</time>
      <time class="class 2">Monday, Wednesday, Friday, 12:20PM to 1:10PM</time>
      <time class="class 3">Monday, Wednesday, Friday, 2:30PM to 3:20PM</time>
      <start>1/21/2020</start>
      <end>5/4/2020</end>
    </course>

    <course subject="chemistry">
      <title>Chemical Principles I Laboratory</title>
      <id>CHEM 1065</id>
      <description>Basic laboratory skills while investigating physical and chemical phenomena closely linked to lecture material. Experimental design, data collection and treatment, discussion of errors, and proper treatment of hazardous wastes.</description>
      <prerequisites>concurrent registration is required (or allowed) in 1061</prerequisites>
      <semester>Spring</semester>
      <units>1 unit</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Michelle Driessen</instructor>
      <instructor name="class 2">Prof. Michelle Driessen</instructor>
      <instructor name="class 3">Prof. Michelle Driessen</instructor>
      <location room="class 1">Smith Hall 110</location>
      <location room="class 2">Smith Hall 110</location>
      <location room="class 3">Smith Hall 110</location>
      <time class="class 1">Monday, 11:15AM to 2:05PM</time>
      <time class="class 2">Monday, 2:30PM to 5:20PM</time>
      <time class="class 3">Tuesday, 8:00AM to 10:50AM</time>
      <start>1/21/2020</start>
      <end>5/4/2020</end>
    </course>

    <course subject="math">
      <title>CSE Multivariable Calculus and Vector Analysis</title>
      <id>2374</id>
      <description>Derivative as linear map. Differential/integral calculus of functions of several variables, including change of coordinates using Jacobians. Line/surface integrals. Gauss, Green, Stokes theorems. Use of computer technology.</description>
      <prerequisites>[1272 or 1282 or 1372 or 1572] w/grade of at least C-, CSE or pre-Bioprod/Biosys Engr</prerequisites>
      <semester>Fall</semester>
      <units>4 units</units>
      <format>In Person</format>
      <instructor name="class 1">Prof. Paul Carter</instructor>
      <instructor name="class 2">Prof. Cheng Chen</instructor>
